[2025-06-03T21:15:25.756+0000] {processor.py:161} INFO - Started process (PID=3081) to work on /opt/airflow/dags/dag_with_python_requirements.py
[2025-06-03T21:15:25.761+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_requirements.py for tasks to queue
[2025-06-03T21:15:25.774+0000] {logging_mixin.py:188} INFO - [2025-06-03T21:15:25.773+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_requirements.py
[2025-06-03T21:15:25.939+0000] {logging_mixin.py:188} INFO - [2025-06-03T21:15:25.923+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_requirements.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_requirements.py", line 1, in <module>
    from datatime import datetime, timedelta
ModuleNotFoundError: No module named 'datatime'
[2025-06-03T21:15:25.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_requirements.py
[2025-06-03T21:15:26.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_requirements.py took 0.349 seconds
[2025-06-03T21:15:48.601+0000] {processor.py:161} INFO - Started process (PID=3090) to work on /opt/airflow/dags/dag_with_python_requirements.py
[2025-06-03T21:15:48.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_python_requirements.py for tasks to queue
[2025-06-03T21:15:48.615+0000] {logging_mixin.py:188} INFO - [2025-06-03T21:15:48.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_requirements.py
[2025-06-03T21:15:49.207+0000] {logging_mixin.py:188} INFO - [2025-06-03T21:15:49.151+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_requirements.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_requirements.py", line 1, in <module>
    from datatime import datetime, timedelta
ModuleNotFoundError: No module named 'datatime'
[2025-06-03T21:15:49.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_requirements.py
[2025-06-03T21:15:49.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_python_requirements.py took 0.678 seconds
