[2025-06-03T19:55:57.737+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-01-02T00:00:00+00:00 [queued]>
[2025-06-03T19:55:57.763+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-01-02T00:00:00+00:00 [queued]>
[2025-06-03T19:55:57.771+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2025-06-03T19:55:57.797+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-01-02 00:00:00+00:00
[2025-06-03T19:55:57.805+0000] {standard_task_runner.py:60} INFO - Started process 30283 to run task
[2025-06-03T19:55:57.815+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2022-01-02T00:00:00+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/postgresql_dag.py', '--cfg-path', '/tmp/tmp9yowymo5']
[2025-06-03T19:55:57.818+0000] {standard_task_runner.py:88} INFO - Job 355: Subtask create_postgres_table
[2025-06-03T19:55:57.913+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2022-01-02T00:00:00+00:00 [running]> on host 4bea2aab752f
[2025-06-03T19:55:58.024+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2022-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-01-02T00:00:00+00:00'
[2025-06-03T19:55:58.026+0000] {sql.py:276} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2025-06-03T19:55:58.037+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-03T19:55:58.055+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-03T19:55:58.080+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Name or service not known

[2025-06-03T19:55:58.101+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20220102T000000, start_date=20250603T195557, end_date=20250603T195558
[2025-06-03T19:55:58.133+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 355 for task create_postgres_table (could not translate host name "host.docker.local" to address: Name or service not known
; 30283)
[2025-06-03T19:55:58.186+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-03T19:55:58.220+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
