[2025-06-03T19:55:53.247+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2021-12-20T00:00:00+00:00 [queued]>
[2025-06-03T19:55:53.299+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2021-12-20T00:00:00+00:00 [queued]>
[2025-06-03T19:55:53.302+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2025-06-03T19:55:53.385+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2021-12-20 00:00:00+00:00
[2025-06-03T19:55:53.429+0000] {standard_task_runner.py:60} INFO - Started process 30216 to run task
[2025-06-03T19:55:53.437+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2021-12-20T00:00:00+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/postgresql_dag.py', '--cfg-path', '/tmp/tmpj2fa534t']
[2025-06-03T19:55:53.440+0000] {standard_task_runner.py:88} INFO - Job 342: Subtask create_postgres_table
[2025-06-03T19:55:53.791+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2021-12-20T00:00:00+00:00 [running]> on host 4bea2aab752f
[2025-06-03T19:55:54.131+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2021-12-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-12-20T00:00:00+00:00'
[2025-06-03T19:55:54.134+0000] {sql.py:276} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2025-06-03T19:55:54.177+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-03T19:55:54.210+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2025-06-03T19:55:54.254+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Name or service not known

[2025-06-03T19:55:54.305+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20211220T000000, start_date=20250603T195553, end_date=20250603T195554
[2025-06-03T19:55:54.345+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 342 for task create_postgres_table (could not translate host name "host.docker.local" to address: Name or service not known
; 30216)
[2025-06-03T19:55:54.414+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-03T19:55:54.684+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
